Homework 1 - [Your team name here]
========================================================

### Task 1 - Implementation

<!--
Use this section to implement the fizzbuzz function.

This should include a short write up describing your approach
to implementing the function. Note that both code formating / style
and your writeup matter for your overall grade.
-->
```{r}
fizzbuzz = function(v)
{for (num in v){
  if (is.complex(num)) {print(num)}
  else if (is.infinite(num)) {print(num)}
  else if (is.character(num)) {print(num)}
  else if (num %% 15==0){print("FizzBuzz")
  break} 
  else if (num %% 3==0){print("Fizz")}
  else if (num %% 5==0){print("Bizz")}
  else {print(num)}
}
}
```

### Task 2 - Validation

<!--
Use this section to show the output of your 
fizzbuzz function for various inputs

No writeup is necessary for this section.
-->

```{r}
fizzbuzz(1)
fizzbuzz(3)
fizzbuzz(5)
fizzbuzz(15)

fizzbuzz(9:15)
fizzbuzz(15:9)

fizzbuzz(-1)
fizzbuzz(-3)
fizzbuzz(-5)

fizzbuzz(Inf)
fizzbuzz(-Inf)

fizzbuzz("A")
fizzbuzz(1.5)
fizzbuzz(1i)
fizzbuzz(4i)
```


